version: '3'
services:
  frontend:
    image: k9-sak-frontend:1.2.0
    # build: .
    ports:
      - 9000:9000
    environment:
      - APP_URL_FPSAK=http://host.docker.internal:8080
      - APP_PORT=9000
      - APP_PATH_PREFIX=fpsak
